# Generated by Django 4.2.9 on 2024-01-28 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('hardware_type', models.IntegerField()),
                ('station_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PositionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('ground_speed', models.FloatField()),
                ('ground_track', models.FloatField()),
                ('updated_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('hardware_node', models.CharField(db_index=True, max_length=64)),
                ('hardware_number', models.IntegerField(db_index=True)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('station_type', models.CharField(max_length=255)),
                ('hardware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalink.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='TextLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='evalink.station')),
                ('position_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalink.positionlog')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalink.station')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('position_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalink.positionlog')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalink.station')),
            ],
        ),
        migrations.AddField(
            model_name='positionlog',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalink.station'),
        ),
        migrations.CreateModel(
            name='NeighborLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.FloatField()),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbor', to='evalink.station')),
                ('position_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evalink.positionlog')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evalink.station')),
            ],
        ),
    ]
