# Generated by Django 4.2.9 on 2024-01-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylog',
            name='barometric_pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='current',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='voltage',
            field=models.FloatField(null=True),
        ),
    ]
