# Generated by Django 4.2.9 on 2024-01-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0002_telemetrylog_barometric_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='hardware_number',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
