# Generated by Django 4.2.9 on 2024-01-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0003_alter_station_hardware_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionlog',
            name='altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='positionlog',
            name='ground_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='positionlog',
            name='ground_track',
            field=models.FloatField(null=True),
        ),
    ]
