# Generated by Django 4.2.9 on 2024-01-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0004_alter_positionlog_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylog',
            name='battery_level',
            field=models.FloatField(null=True),
        ),
    ]
