# Generated by Django 4.2.9 on 2024-01-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0005_telemetrylog_battery_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
