# Generated by Django 4.2.9 on 2024-02-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0012_textlog_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='last_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_position', to='evalink.positionlog'),
        ),
    ]
