# Generated by Django 4.2.9 on 2024-03-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0014_campus_crew_crewmember_eva_evacrewmember_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='firmware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='textlog',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='evalink.station'),
        ),
    ]
