# Generated by Django 4.2.9 on 2024-04-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0015_alter_station_firmware_alter_textlog_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='hardware_type',
            field=models.IntegerField(),
        ),
    ]
