# Generated by Django 4.2.9 on 2024-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0016_alter_hardware_hardware_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hardware',
            constraint=models.UniqueConstraint(fields=('name', 'hardware_type'), name='unique_name_hardware_type'),
        ),
    ]
