# Generated by Django 4.2.9 on 2024-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0017_hardware_unique_name_hardware_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hardware',
            name='unique_name_hardware_type',
        ),
        migrations.AddConstraint(
            model_name='hardware',
            constraint=models.UniqueConstraint(fields=('station_type', 'hardware_type'), name='unique_station_type_hardware_type'),
        ),
    ]
