# Generated by Django 4.2.9 on 2024-07-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0018_remove_hardware_unique_name_hardware_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude1', models.FloatField()),
                ('longitude1', models.FloatField()),
                ('latitude2', models.FloatField()),
                ('longitude2', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='inner_geofence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_campus_set', to='evalink.geofence'),
        ),
        migrations.AddField(
            model_name='campus',
            name='outer_geofence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outer_campus_set', to='evalink.geofence'),
        ),
    ]
