# Generated by Django 4.2.9 on 2024-07-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0019_geofence_campus_inner_geofence_campus_outer_geofence'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='time_zone',
            field=models.TextField(default='America/Denver'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='inner_geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inner_campus_set', to='evalink.geofence'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='outer_geofence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outer_campus_set', to='evalink.geofence'),
        ),
    ]
