# Generated by Django 4.2.16 on 2024-12-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0020_campus_time_zone_alter_campus_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionlog',
            name='timestamp',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
