# Generated by Django 4.2.16 on 2025-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0021_positionlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylog',
            name='wind_direction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='wind_gust',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='wind_lull',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
    ]
