# Generated by Django 4.2.16 on 2025-05-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0022_telemetrylog_wind_direction_telemetrylog_wind_gust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylog',
            name='message_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
