# Generated by Django 4.2.16 on 2025-05-04 16:23

from django.db import migrations

def set_default_id(apps, _schema_editor):
    ModelName = apps.get_model('evalink', 'TelemetryLog')
    for obj in ModelName.objects.all():
        obj.message_id = obj.id
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0023_telemetrylog_message_id'),
    ]

    operations = [
        migrations.RunPython(set_default_id),
    ]
