# Generated by Django 4.2.16 on 2025-05-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0024_auto_20250504_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrylog',
            name='message_id',
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
    ]
