# Generated by Django 4.2.16 on 2025-05-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0025_alter_telemetrylog_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionlog',
            name='message_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='positionlog',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='positionlog',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
    ]
