# Generated by Django 4.2.16 on 2025-05-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0026_positionlog_message_id_alter_positionlog_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionlog',
            name='updated_on',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='updated_on',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
