# Generated by Django 4.2.16 on 2025-05-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0027_positionlog_updated_on_telemetrylog_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrylog',
            name='position_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='evalink.positionlog'),
        ),
        migrations.AlterField(
            model_name='textlog',
            name='position_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='evalink.positionlog'),
        ),
    ]
