# Generated by Django 4.2.16 on 2025-05-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0028_alter_telemetrylog_position_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborlog',
            name='position_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evalink.positionlog'),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='position_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evalink.positionlog'),
        ),
    ]
