# Generated by Django 4.2.16 on 2025-12-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0032_add_updated_on_to_textlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(db_index=True, max_length=255)),
                ('features', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_on', models.DateField(db_index=True, null=True)),
            ],
        ),
    ]
