# Generated by Django 4.2.16 on 2025-12-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0033_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='campus',
            field=models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, to='evalink.campus'),
        ),
    ]
