# Generated by Django 4.2.16 on 2025-12-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0034_aircraft_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='hex',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
