# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalink', '0035_alter_aircraft_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='APRSPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(db_index=True, max_length=32, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=16, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
